const API_BASE=(window.LENSFIND_API_BASE||'').replace(/\/$/,'');
const events=[];let currentEventId=null;let localPhotos=[];let eventCounter=1;
function eventCard(e){return `<article class="event-card"><div class="event-image one"><span class="event-status">● ${e.status||'READY'}</span></div><div class="event-body"><h3>${e.name}</h3><p class="muted">${e.date||'—'}</p><div class="event-meta"><span>📷 ${e.photos||0} photos</span><span>Local upload</span></div><div class="event-footer"><button class="secondary-btn" onclick="openQr('${e.id}')">QR code</button><button class="primary-btn" onclick="openGuest('${e.id}')">Open event</button></div></div></article>`}
function renderEvents(){document.getElementById('eventGrid').innerHTML=events.map(eventCard).join('')||'<p class="muted">No events yet. Create your first event.</p>';document.getElementById('allEvents').innerHTML=events.map(eventCard).join('')||'<p class="muted">No events yet.</p>'}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});document.querySelector('.topnav')?.classList.remove('mobile-open')}
function openGuest(id=''){currentEventId=id||currentEventId;showPage('guest')}
function openQr(id=''){currentEventId=id||currentEventId;showPage('qr');const e=events.find(x=>x.id===currentEventId);const link=e?`${location.origin}${location.pathname}?event=${encodeURIComponent(e.id)}&view=guest`:location.href;document.querySelector('#qr .qr-card strong').textContent=link;document.querySelector('#qr .qr-meta').innerHTML=e?`<span>${e.name}</span><span>${e.photos} photos</span><span>Local upload</span>`:''}
function openResults(){showPage('results');renderPhotos()}
function renderPhotos(){const e=events.find(x=>x.id===currentEventId);document.querySelector('#results .muted').textContent=e?`${e.photos} photos uploaded from your computer.`:'Select an event first.';document.getElementById('photoGrid').innerHTML=localPhotos.length?localPhotos.map(p=>`<div class="photo" style="background-image:url('${p.url}');background-size:cover;background-position:center"><span>${p.name}</span></div>`).join(''):'<p class="muted">No photos uploaded yet.</p>'}
function newEvent(){document.getElementById('eventModal').classList.remove('hidden');document.getElementById('eventName').focus()}
function setupCamera(){const modal=document.createElement('div');modal.className='camera-modal';modal.innerHTML=`<div class="camera-card"><button class="close camera-close">×</button><p class="eyebrow">SELFIE SEARCH</p><h2>Take your selfie</h2><div class="camera-frame"><video autoplay playsinline muted></video><div class="face-guide"></div></div><p class="muted camera-status">Allow camera access, then centre your face.</p><div class="camera-actions"><button class="secondary-btn camera-close">Cancel</button><button class="primary-btn capture-btn">Capture & find photos</button></div></div>`;document.body.appendChild(modal);const video=modal.querySelector('video');let stream=null;const stop=()=>{stream?.getTracks().forEach(t=>t.stop());modal.remove()};modal.querySelectorAll('.camera-close').forEach(b=>b.onclick=stop);navigator.mediaDevices?.getUserMedia({video:{facingMode:'user'},audio:false}).then(s=>{stream=s;video.srcObject=s}).catch(()=>{modal.querySelector('.camera-status').textContent='Camera permission was not granted. Use the uploaded-photo test instead.'});modal.querySelector('.capture-btn').onclick=()=>{stop();openResults()}}
function previewLocalFiles(){const input=document.getElementById('localPhotos');const files=[...input.files].filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));const box=document.getElementById('uploadPreview');box.innerHTML=files.length?`<strong>${files.length} photo${files.length>1?'s':''} selected</strong><small>Ready to upload from this computer</small>`:'<span>No photos selected</span>';box.dataset.count=files.length;if(files.length!==input.files.length)box.innerHTML='<strong>Only JPG, PNG or WEBP images are supported.</strong>';}
async function createLocalEvent(){const button=document.getElementById('createEvent');const name=document.getElementById('eventName').value.trim()||'New Photography Event';const date=document.getElementById('eventDate').value||'Local test';const files=[...document.getElementById('localPhotos').files].filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));if(!files.length){document.getElementById('uploadPreview').innerHTML='<strong>Please choose at least one JPG, PNG or WEBP photo.</strong>';return}button.disabled=true;const original=button.textContent;button.textContent='Uploading…';try{const id=`local-${Date.now()}-${eventCounter++}`;localPhotos.forEach(p=>URL.revokeObjectURL(p.url));localPhotos=files.map(file=>({name:file.name,url:URL.createObjectURL(file),file}));events.unshift({id,name,date,photos:files.length,status:'READY'});currentEventId=id;renderEvents();document.getElementById('eventModal').classList.add('hidden');document.getElementById('eventName').value='';document.getElementById('eventDate').value='';document.getElementById('localPhotos').value='';document.getElementById('uploadPreview').innerHTML='';showPage('events');openResults();}catch(error){console.error(error);alert('Upload failed. Please refresh the page and try again.')}finally{button.disabled=false;button.textContent=original}}
document.getElementById('newEventBtn').addEventListener('click',newEvent);document.getElementById('newEventBtn2').addEventListener('click',newEvent);document.getElementById('closeModal').addEventListener('click',()=>document.getElementById('eventModal').classList.add('hidden'));document.getElementById('viewGuestBtn').addEventListener('click',()=>openGuest());document.getElementById('selfieBtn').addEventListener('click',setupCamera);document.getElementById('demoMatchBtn').addEventListener('click',openResults);document.getElementById('backGuestBtn').addEventListener('click',()=>openGuest(currentEventId));document.getElementById('localPhotos').addEventListener('change',previewLocalFiles);document.getElementById('createEvent').addEventListener('click',createLocalEvent);document.getElementById('copyLinkBtn').addEventListener('click',async()=>{const link=document.querySelector('#qr .qr-card strong').textContent;try{await navigator.clipboard.writeText(link);document.getElementById('copyLinkBtn').textContent='Copied ✓';setTimeout(()=>document.getElementById('copyLinkBtn').textContent='Copy guest link',1800)}catch{alert(link)}});document.querySelectorAll('.topnav a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showPage(a.getAttribute('href').slice(1))}));document.getElementById('menuBtn').addEventListener('click',()=>document.querySelector('.topnav').classList.toggle('mobile-open'));
const eventParam=new URLSearchParams(location.search).get('event');if(eventParam){currentEventId=eventParam;showPage('guest')}renderEvents();
