const events=[{name:'Riya & Arjun Wedding',date:'29 Aug 2026',photos:'2,458',status:'LIVE',image:'one',processed:'98%'},{name:'Ananya Birthday',date:'24 Aug 2026',photos:'856',status:'LIVE',image:'two',processed:'100%'},{name:'Kolkata Portrait Day',date:'18 Aug 2026',photos:'1,126',status:'PROCESSING',image:'three',processed:'72%'}];
const photoLabels=['Ceremony','Candid','Group moment','Reception','Portrait','Stage','Family','Dance','Candid','Friends','Couple','Celebration'];
let activeFilter='All';
function eventCard(e){return `<article class="event-card"><div class="event-image ${e.image}"><span class="event-status">● ${e.status}</span></div><div class="event-body"><h3>${e.name}</h3><p class="muted">${e.date}</p><div class="event-meta"><span>📷 ${e.photos} photos</span><span>${e.processed} indexed</span></div><div class="event-footer"><button class="secondary-btn" onclick="openQr()">QR code</button><button class="primary-btn" onclick="openGuest()">Open event</button></div></div></article>`}
function renderEvents(){document.getElementById('eventGrid').innerHTML=events.map(eventCard).join('');document.getElementById('allEvents').innerHTML=events.map(eventCard).join('')}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});closeMobileNav()}
function openGuest(){showPage('guest')} function openQr(){showPage('qr')} function openResults(){showPage('results');renderPhotos()}
function renderPhotos(){const labels=activeFilter==='All'?photoLabels:photoLabels.filter(x=>x.toLowerCase().includes(activeFilter.toLowerCase()));const count=activeFilter==='All'?42:activeFilter==='Candid'?18:activeFilter==='Group'?14:10;document.querySelector('#results .muted').textContent=`${count} photos found in this event.`;document.getElementById('photoGrid').innerHTML=Array.from({length:count},(_,i)=>`<div class="photo"><span>${labels[i%labels.length]||activeFilter} · ${String(i+1).padStart(2,'0')}</span></div>`).join('')}
function newEvent(){document.getElementById('eventModal').classList.remove('hidden');document.getElementById('eventName').focus()}
function closeMobileNav(){document.querySelector('.topnav')?.classList.remove('mobile-open')}
function setupCamera(){const modal=document.createElement('div');modal.className='camera-modal';modal.innerHTML=`<div class="camera-card"><button class="close camera-close">×</button><p class="eyebrow">SELFIE SEARCH</p><h2>Take your selfie</h2><div class="camera-frame"><video autoplay playsinline muted></video><div class="face-guide"></div></div><p class="muted camera-status">Allow camera access, then centre your face.</p><div class="camera-actions"><button class="secondary-btn camera-close">Cancel</button><button class="primary-btn capture-btn">Capture & find photos</button></div></div>`;document.body.appendChild(modal);const video=modal.querySelector('video');let stream=null;const stop=()=>{stream?.getTracks().forEach(t=>t.stop());modal.remove()};modal.querySelectorAll('.camera-close').forEach(b=>b.onclick=stop);navigator.mediaDevices?.getUserMedia({video:{facingMode:'user'},audio:false}).then(s=>{stream=s;video.srcObject=s}).catch(()=>{modal.querySelector('.camera-status').textContent='Camera permission was not granted. You can still use the demo results.'});modal.querySelector('.capture-btn').onclick=()=>{stop();openResults()}}
document.getElementById('newEventBtn').onclick=newEvent;document.getElementById('newEventBtn2').onclick=newEvent;document.getElementById('closeModal').onclick=()=>document.getElementById('eventModal').classList.add('hidden');document.getElementById('viewGuestBtn').onclick=openGuest;
document.getElementById('selfieBtn').onclick=setupCamera;document.getElementById('demoMatchBtn').onclick=openResults;document.getElementById('backGuestBtn').onclick=openGuest;
document.getElementById('copyLinkBtn').onclick=async()=>{try{await navigator.clipboard.writeText('https://lensfind.app/w/wed290826');document.getElementById('copyLinkBtn').textContent='Copied ✓';setTimeout(()=>document.getElementById('copyLinkBtn').textContent='Copy guest link',1800)}catch{alert('Guest link: https://lensfind.app/w/wed290826')}};
document.getElementById('createEvent').onclick=()=>{const n=document.getElementById('eventName').value.trim()||'New Photography Event';events.unshift({name:n,date:'New event',photos:'0',status:'READY',image:'two',processed:'0%'});renderEvents();document.getElementById('eventModal').classList.add('hidden');document.getElementById('eventName').value='';showPage('events')};
document.querySelectorAll('.topnav a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showPage(a.getAttribute('href').slice(1))}));
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');activeFilter=button.textContent.split(' ')[0];renderPhotos()}));
document.getElementById('menuBtn').onclick=()=>document.querySelector('.topnav').classList.toggle('mobile-open');
renderEvents();